basePath: /api/v1
definitions:
  management.Registration:
    properties:
      key:
        example: f2ca1bb6c7e907d06dafe4687e579fce76b37e4e93b7605022da52e6ccc26fd2
        type: string
      name:
        example: John Doe
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/agent/management/register:
    post:
      consumes:
      - application/json
      description: register agent
      parameters:
      - description: Agent registration information
        in: body
        name: registration
        required: true
        schema:
          $ref: '#/definitions/management.Registration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: register agent to the server
      tags:
      - agent management
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
