version: "3.8"

services:
  api:
    container_name: api
    restart: always
    depends_on:
      valkey:
        condition: service_started
      manticore:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8080"
    networks:
      - go-network
    environment:
      - REDIS_PASS=${REDIS_PASS}
      - SECRET=${SECRET}
      - API_ADMIN=${API_ADMIN}
      - MANTICORE_HOST=${MANTICORE_HOST}
    volumes:
      # - ./:/api
      - ./db/data:/db
  valkey: # you can switch this out for redis
    image: valkey/valkey:9-alpine
    container_name: valkey
    restart: always
    command: valkey-server --requirepass ${REDIS_PASS}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - go-network
  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    restart: always
    volumes:
      - ./.data:/var/lib/manticore
      # - ./certs:/etc/manticoresearch/certs
      # - ./manticore.conf:/etc/manticoresearch/manticore.conf
    ports:
      - 127.0.0.1:9306:9306
      - 127.0.0.1:9308:9308
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    
    networks:
      - go-network

networks:
  go-network:
    driver: bridge

volumes:
  valkey_data: